<?xml version="1.0" encoding="utf-8" ?>
<!--<!DOCTYPE note SYSTEM "description.dtd">-->
<!DOCTYPE description [
        <!ELEMENT description (project,project_name,project_version,project_year,project_month,project_day,project_description,docu_author)>
        <!ELEMENT project (project_name,project_version,project_year,project_month,project_day,project_description,docu_author)>
        <!ELEMENT project_name (#PCDATA)>
        <!ELEMENT project_version (#PCDATA)>
        <!ELEMENT project_year (#PCDATA)>
        <!ELEMENT project_month (#PCDATA)>
        <!ELEMENT project_day (#PCDATA)>
        <!ELEMENT project_description (#PCDATA)>
        <!ELEMENT docu_author (#PCDATA)>
        ]>
<description>
    <project>
        <project_name>web</project_name>
        <project_version>1.0</project_version>
        <project_year>2017</project_year>
        <project_month>12</project_month>
        <project_day>20</project_day>
        <project_description>this is a web project</project_description>
        <docu_author>GH</docu_author>
    </project>
</description>